### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by Larnicone**
I hope it helps. :)

### CODE REVIEW

**Comment by TheLastProject** [comment]
Your PR removes the English translation, but this is still very useful! I'll include this in the next release, thank you!

**Comment by TheLastProject** [comment]
Okay, restored English. Thank you for the translation!

**Comment by Larnicone** [comment]
Oh, sorry, it never done this before. That was not my intention.  :)

**Comment by TheLastProject** [comment]
No worries, you were still super helpful anyway!

**Comment by TheLastProject** [comment]
Hey, I added some new stuff to translate. Please see https://github.com/TheLastProject/RaiseToAnswer/blob/master/app/src/main/res/values/strings.xml for the list of all sentences and https://github.com/TheLastProject/RaiseToAnswer/blob/master/app/src/main/res/values-fr/strings.xml for the current French translations. If you want to add these too, that is :)

**Pull request merged**
